name: Release

on: workflow_dispatch

permissions:
  contents: write
  discussions: write
  packages: read

jobs:
  release:
    name: Create Release
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
          pip freeze > outdated.txt
          pip install -r outdated.txt --upgrade
          pip install -r requirements.txt

    - name: Install UPX
      uses: crazy-max/ghaction-upx@v2
      with:
        install-only: true

    - name: Get build name & version
      shell: bash
      id: get_info
      run: |
        NAME=$(python build.py --name)
        VERSION=$(python build.py --version)
        echo "NAME=${NAME}" >> $GITHUB_OUTPUT
        echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT

    - name: Build executable
      run: python build.py

    - name: Rename executable
      shell: bash
      run: mv "${{ steps.get_info.outputs.NAME }}-v${{ steps.get_info.outputs.VERSION }}.exe" "${{ steps.get_info.outputs.NAME }}-v${{ steps.get_info.outputs.VERSION }}-windows-x86_64.exe"

    - name: ZIP Full Tilt! Pinball - Space Cadet
      uses: TheDoctor0/zip-release@0.7.1
      with:
        type: zip
        filename: Full-Tilt!-Pinball-Space-Cadet.zip
        path: boards/Cadet/.

    - name: ZIP Full Tilt! Pinball - Skullduggery
      uses: TheDoctor0/zip-release@0.7.1
      with:
        type: zip
        filename: Full-Tilt!-Pinball-Skullduggery.zip
        path: boards/Pirates/.

    - name: ZIP Full Tilt! Pinball - Dragon's Keep
      uses: TheDoctor0/zip-release@0.7.1
      with:
        type: zip
        filename: Full-Tilt!-Pinball-Dragon's-Keep.zip
        path: boards/Dragon/.

    - name: ZIP Full Tilt! Pinball 2 - Mad Scientist
      uses: TheDoctor0/zip-release@0.7.1
      with:
        type: zip
        filename: Full-Tilt!-Pinball-2-Mad-Scientist.zip
        path: boards/Mad/.

    - name: ZIP Full Tilt! Pinball 2 - Captain Hero
      uses: TheDoctor0/zip-release@0.7.1
      with:
        type: zip
        filename: Full-Tilt!-Pinball-2-Captain-Hero.zip
        path: boards/Hero/.

    - name: ZIP Full Tilt! Pinball 2 - Alien Daze
      uses: TheDoctor0/zip-release@0.7.1
      with:
        type: zip
        filename: Full-Tilt!-Pinball-2-Alien-Daze.zip
        path: boards/Alien/.

    - name: List files
      shell: bash
      run: ls -la
