name: Release

on: workflow_dispatch

permissions:
  contents: write
  discussions: write
  packages: read

jobs:
  release:
    name: Create Release
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
          pip freeze > outdated.txt
          pip install -r outdated.txt --upgrade
          pip install -r requirements.txt

    - name: Install UPX
      uses: crazy-max/ghaction-upx@v2
      with:
        install-only: true

    - name: Get build name & version
      shell: bash
      id: get_info
      run: |
        NAME=$(python build.py --name)
        VERSION=$(python build.py --version)
        echo "NAME=${NAME}" >> $GITHUB_OUTPUT
        echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT

    - name: Build executable
      run: python build.py

    - name: Rename executable
      shell: bash
      run: mv "${{ steps.get_info.outputs.NAME }}-v${{ steps.get_info.outputs.VERSION }}.exe" "${{ steps.get_info.outputs.NAME }}-v${{ steps.get_info.outputs.VERSION }}-windows-x86_64.exe"

    - name: ZIP Full Tilt! Pinball - Space Cadet
      uses: TheDoctor0/zip-release@0.7.1
      with:
        type: zip
        custom: -mm=LZMA -mx=9 -mfb=256 -md=1024m
        filename: Full-Tilt!-Pinball-Space-Cadet.zip
        path: boards/Cadet/.

    - name: ZIP Full Tilt! Pinball - Skullduggery
      uses: TheDoctor0/zip-release@0.7.1
      with:
        type: zip
        custom: -mm=LZMA -mx=9 -mfb=256 -md=1024m
        filename: Full-Tilt!-Pinball-Skullduggery.zip
        path: boards/Pirates/.

    - name: ZIP Full Tilt! Pinball - Dragon's Keep
      uses: TheDoctor0/zip-release@0.7.1
      with:
        type: zip
        custom: -mm=LZMA -mx=9 -mfb=256 -md=1024m
        filename: Full-Tilt!-Pinball-Dragon's-Keep.zip
        path: boards/Dragon/.

    - name: ZIP Full Tilt! Pinball 2 - Mad Scientist
      uses: TheDoctor0/zip-release@0.7.1
      with:
        type: zip
        custom: -mm=LZMA -mx=9 -mfb=256 -md=1024m
        filename: Full-Tilt!-Pinball-2-Mad-Scientist.zip
        path: boards/Mad/.

    - name: ZIP Full Tilt! Pinball 2 - Captain Hero
      uses: TheDoctor0/zip-release@0.7.1
      with:
        type: zip
        custom: -mm=LZMA -mx=9 -mfb=256 -md=1024m
        filename: Full-Tilt!-Pinball-2-Captain-Hero.zip
        path: boards/Hero/.

    - name: ZIP Full Tilt! Pinball 2 - Alien Daze
      uses: TheDoctor0/zip-release@0.7.1
      with:
        type: zip
        custom: -mm=LZMA -mx=9 -mfb=256 -md=1024m
        filename: Full-Tilt!-Pinball-2-Alien-Daze.zip
        path: boards/Alien/.

    - name: VirusTotal Scan
      uses: crazy-max/ghaction-virustotal@v3.2.0
      id: vt_scan
      with:
        vt_api_key: ${{ secrets.VT_API_KEY }}
        request_rate: 4
        files: |
            Full-Tilt!-Pinball-Space-Cadet.zip
            Full-Tilt!-Pinball-Skullduggery.zip
            Full-Tilt!-Pinball-Dragon's-Keep.zip
            Full-Tilt!-Pinball-2-Mad-Scientist.zip
            Full-Tilt!-Pinball-2-Captain-Hero.zip
            Full-Tilt!-Pinball-2-Alien-Daze.zip
            ${{ steps.get_info.outputs.NAME }}-v${{ steps.get_info.outputs.VERSION }}-windows-x86_64.exe

    - name: test scan output
      run: |
        echo "${{ steps.vt_scan.outputs.analysis }}"
        exit 1

    - name: VirusTotal Scan Results
      shell: bash
      id: vt_results
      run: |
        IFS=',' read -r -a array <<< "${{ steps.vt_scan.outputs.analysis }}"
        LAUNCHER=
        LAUNCHER_URL=
        SPACE_CADET=
        SPACE_CADET_URL=
        SKULLDUGGERY=
        SKULLDUGGERY_URL=
        DRAGONS_KEEP=
        DRAGONS_KEEP_URL=
        MAD_SCIENTIST=
        MAD_SCIENTIST_URL=
        CAPTAIN_HERO=
        CAPTAIN_HERO_URL=
        ALIEN_DAZE=
        ALIEN_DAZE_URL=
        echo "LAUNCHER=${LAUNCHER}" >> $GITHUB_OUTPUT
        echo "LAUNCHER_URL=${LAUNCHER_URL}" >> $GITHUB_OUTPUT
        echo "SPACE_CADET=${SPACE_CADET}" >> $GITHUB_OUTPUT
        echo "SPACE_CADET_URL=${SPACE_CADET_URL}" >> $GITHUB_OUTPUT
        echo "SKULLDUGGERY=${SKULLDUGGERY}" >> $GITHUB_OUTPUT
        echo "SKULLDUGGERY_URL=${SKULLDUGGERY_URL}" >> $GITHUB_OUTPUT
        echo "DRAGONS_KEEP=${DRAGONS_KEEP}" >> $GITHUB_OUTPUT
        echo "DRAGONS_KEEP_URL=${DRAGONS_KEEP_URL}" >> $GITHUB_OUTPUT
        echo "MAD_SCIENTIST=${MAD_SCIENTIST}" >> $GITHUB_OUTPUT
        echo "MAD_SCIENTIST_URL=${MAD_SCIENTIST_URL}" >> $GITHUB_OUTPUT
        echo "CAPTAIN_HERO=${CAPTAIN_HERO}" >> $GITHUB_OUTPUT
        echo "CAPTAIN_HERO_URL=${CAPTAIN_HERO_URL}" >> $GITHUB_OUTPUT
        echo "ALIEN_DAZE=${ALIEN_DAZE}" >> $GITHUB_OUTPUT
        echo "ALIEN_DAZE_URL=${ALIEN_DAZE_URL}" >> $GITHUB_OUTPUT

    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        body: |
          ### **_${{ steps.get_info.outputs.NAME }}-v${{ steps.get_info.outputs.VERSION }}_**

          [VirusTotal](https://www.virustotal.com/) analysis:
          - [${{ steps.vt_results.outputs.LAUNCHER }}](${{ steps.vt_results.outputs.LAUNCHER_URL }})
          - [${{ steps.vt_results.outputs.SPACE_CADET }}](${{ steps.vt_results.outputs.SPACE_CADET_URL }})
          - [${{ steps.vt_results.outputs.SKULLDUGGERY }}](${{ steps.vt_results.outputs.SKULLDUGGERY_URL }})
          - [${{ steps.vt_results.outputs.DRAGONS_KEEP }}](${{ steps.vt_results.outputs.DRAGONS_KEEP_URL }})
          - [${{ steps.vt_results.outputs.MAD_SCIENTIST }}](${{ steps.vt_results.outputs.MAD_SCIENTIST_URL }})
          - [${{ steps.vt_results.outputs.CAPTAIN_HERO }}](${{ steps.vt_results.outputs.CAPTAIN_HERO_URL }})
          - [${{ steps.vt_results.outputs.ALIEN_DAZE }}](${{ steps.vt_results.outputs.ALIEN_DAZE_URL }})
        draft: false
        prerelease: false
        files: |
          "Full-Tilt!-Pinball-Space-Cadet.zip"
          "Full-Tilt!-Pinball-Skullduggery.zip"
          "Full-Tilt!-Pinball-Dragon's-Keep.zip"
          "Full-Tilt!-Pinball-2-Mad-Scientist.zip"
          "Full-Tilt!-Pinball-2-Captain-Hero.zip"
          "Full-Tilt!-Pinball-2-Alien-Daze.zip"
          "${{ steps.get_info.outputs.NAME }}-v${{ steps.get_info.outputs.VERSION }}-windows-x86_64.exe"
        name: v${{ steps.get_info.outputs.VERSION }}
        tag_name: v${{ steps.get_info.outputs.VERSION }}
        fail_on_unmatched_files: true
        token: ${{ secrets.GITHUB_TOKEN }}