name: Release

on: workflow_dispatch

permissions:
  contents: write
  discussions: write
  packages: read

jobs:
  release:
    name: Create Release
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
          pip freeze > outdated.txt
          pip install -r outdated.txt --upgrade
          pip install -r requirements.txt

    - name: Install UPX
      uses: crazy-max/ghaction-upx@v2
      with:
        install-only: true

    - name: Get build name & version
      shell: bash
      id: get_info
      run: |
        NAME=$(python build.py --name)
        VERSION=$(python build.py --version)
        echo "NAME=${NAME}" >> $GITHUB_OUTPUT
        echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT

    - name: Build executable
      run: python build.py

    - name: Rename executable
      shell: bash
      run: mv "${{ steps.get_info.outputs.NAME }}-v${{ steps.get_info.outputs.VERSION }}.exe" "${{ steps.get_info.outputs.NAME }}-v${{ steps.get_info.outputs.VERSION }}-windows-x86_64.exe"

    - name: ZIP 3D Pinball for Windows - Space Cadet
      uses: TheDoctor0/zip-release@0.7.1
      with:
        type: zip
        custom: -mm=LZMA -mx=9 -mfb=256 -md=1024m
        filename: 3D-Pinball-for-Windows-Space-Cadet.zip
        path: boards/3D Pinball for Windows - Space Cadet/.

    - name: ZIP Full Tilt! Pinball - Space Cadet
      uses: TheDoctor0/zip-release@0.7.1
      with:
        type: zip
        custom: -mm=LZMA -mx=9 -mfb=256 -md=1024m
        filename: Full-Tilt!-Pinball-Space-Cadet.zip
        path: boards/Cadet/.

    - name: ZIP Full Tilt! Pinball - Skullduggery
      uses: TheDoctor0/zip-release@0.7.1
      with:
        type: zip
        custom: -mm=LZMA -mx=9 -mfb=256 -md=1024m
        filename: Full-Tilt!-Pinball-Skullduggery.zip
        path: boards/Pirates/.

    - name: ZIP Full Tilt! Pinball - Dragon's Keep
      uses: TheDoctor0/zip-release@0.7.1
      with:
        type: zip
        custom: -mm=LZMA -mx=9 -mfb=256 -md=1024m
        filename: Full-Tilt!-Pinball-Dragon's-Keep.zip
        path: boards/Dragon/.

    - name: ZIP Full Tilt! Pinball 2 - Mad Scientist
      uses: TheDoctor0/zip-release@0.7.1
      with:
        type: zip
        custom: -mm=LZMA -mx=9 -mfb=256 -md=1024m
        filename: Full-Tilt!-Pinball-2-Mad-Scientist.zip
        path: boards/Mad/.

    - name: ZIP Full Tilt! Pinball 2 - Captain Hero
      uses: TheDoctor0/zip-release@0.7.1
      with:
        type: zip
        custom: -mm=LZMA -mx=9 -mfb=256 -md=1024m
        filename: Full-Tilt!-Pinball-2-Captain-Hero.zip
        path: boards/Hero/.

    - name: ZIP Full Tilt! Pinball 2 - Alien Daze
      uses: TheDoctor0/zip-release@0.7.1
      with:
        type: zip
        custom: -mm=LZMA -mx=9 -mfb=256 -md=1024m
        filename: Full-Tilt!-Pinball-2-Alien-Daze.zip
        path: boards/Alien/.

    - name: VirusTotal Scan
      uses: crazy-max/ghaction-virustotal@v3.2.0
      id: vt_scan
      with:
        vt_api_key: ${{ secrets.VT_API_KEY }}
        request_rate: 1
        files: |
          ${{ steps.get_info.outputs.NAME }}-v${{ steps.get_info.outputs.VERSION }}-windows-x86_64.exe
          3D-Pinball-for-Windows-Space-Cadet.zip
          Full-Tilt!-Pinball-Space-Cadet.zip
          Full-Tilt!-Pinball-Skullduggery.zip
          Full-Tilt!-Pinball-Dragon's-Keep.zip
          Full-Tilt!-Pinball-2-Mad-Scientist.zip
          Full-Tilt!-Pinball-2-Captain-Hero.zip
          Full-Tilt!-Pinball-2-Alien-Daze.zip

    - name: VirusTotal Scan Results
      shell: bash
      id: vt_results
      run: |
        RESULTS_STRING="[VirusTotal](https://www.virustotal.com/) analysis:"$'\n'
        IFS=',' read -r -a array <<< "${{ steps.vt_scan.outputs.analysis }}"
        for element in "${array[@]}"
        do
          IFS='=' read -r -a array2 <<< "$element"
          RESULTS_STRING+="- [${array2[0]}](${array2[1]}==/detection)"$'\n'
        done
        echo "${RESULTS_STRING}"
        EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
        echo "RESULTS<<$EOF" >> "$GITHUB_OUTPUT"
        echo "${RESULTS_STRING}" >> "$GITHUB_OUTPUT"
        echo "$EOF" >> "$GITHUB_OUTPUT"

    - name: Show info
      run: |
        echo "${{ steps.get_info.outputs.NAME }}"
        echo "${{ steps.get_info.outputs.VERSION }}"
        echo "${{ steps.vt_results.outputs.RESULTS }}"
    
    - name: Check if this version was already released
      uses: mukunku/tag-exists-action@v1.2.0
      id: checkTag
      with:
        tag: 'v${{ steps.get_info.outputs.VERSION }}'

    - name: Terminate if this version was already released
      shell: bash
      if: steps.checkTag.outputs.exists == 'true'
      run: |
        echo "v${{ steps.get_info.outputs.VERSION }} was already released!" >&2
        exit 1

    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        body: |
          ### **_${{ steps.get_info.outputs.NAME }}-v${{ steps.get_info.outputs.VERSION }}_**

          ${{ steps.vt_results.outputs.RESULTS }}
        draft: false
        prerelease: false
        files: |
          ${{ steps.get_info.outputs.NAME }}-v${{ steps.get_info.outputs.VERSION }}-windows-x86_64.exe
          3D-Pinball-for-Windows-Space-Cadet.zip
          Full-Tilt!-Pinball-Space-Cadet.zip
          Full-Tilt!-Pinball-Skullduggery.zip
          Full-Tilt!-Pinball-Dragon's-Keep.zip
          Full-Tilt!-Pinball-2-Mad-Scientist.zip
          Full-Tilt!-Pinball-2-Captain-Hero.zip
          Full-Tilt!-Pinball-2-Alien-Daze.zip
        name: v${{ steps.get_info.outputs.VERSION }}
        tag_name: v${{ steps.get_info.outputs.VERSION }}
        fail_on_unmatched_files: true
        token: ${{ secrets.GITHUB_TOKEN }}
